/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// ⚠️ DEPRECATED: This file is kept for backward compatibility only
// 
// SECURITY NOTICE: The hardcoded credentials in this file have been moved to 
// environment variables for better security. Please use utils/supabase/config.tsx 
// instead, which reads from environment variables with fallbacks.
//
// To use the new secure configuration:
// 1. Add VITE_SUPABASE_PROJECT_ID and VITE_SUPABASE_ANON_KEY to your .env.local
// 2. Update imports to use: import { supabaseConfig } from './config'
// 3. Use supabaseConfig.projectId and supabaseConfig.publicAnonKey
//
// This file will be removed in a future version.

export const projectId = "oszvutpdvkfldsmdbzje"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zenZ1dHBkdmtmbGRzbWRiemplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTYxMzEsImV4cCI6MjA2Njk5MjEzMX0.43yoMlVDHJPG4QbH_6EirYVy8AYoPKKvD17f6fhCkyw"